/* 
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GroupConfirmFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupConfirmFileTests
    {
        // TODO uncomment below to declare an instance variable for GroupConfirmFile
        //private GroupConfirmFile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupConfirmFile
            //instance = new GroupConfirmFile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupConfirmFile
        /// </summary>
        [Test]
        public void GroupConfirmFileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupConfirmFile
            //Assert.IsInstanceOfType<GroupConfirmFile> (instance, "variable 'instance' is a GroupConfirmFile");
        }



    }

}
