/* 
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Numbertype16
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Numbertype16Tests
    {
        // TODO uncomment below to declare an instance variable for Numbertype16
        //private Numbertype16 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Numbertype16
            //instance = new Numbertype16();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Numbertype16
        /// </summary>
        [Test]
        public void Numbertype16InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Numbertype16
            //Assert.IsInstanceOfType<Numbertype16> (instance, "variable 'instance' is a Numbertype16");
        }



    }

}
