/* 
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TemplateData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemplateDataTests
    {
        // TODO uncomment below to declare an instance variable for TemplateData
        //private TemplateData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateData
            //instance = new TemplateData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateData
        /// </summary>
        [Test]
        public void TemplateDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplateData
            //Assert.IsInstanceOfType<TemplateData> (instance, "variable 'instance' is a TemplateData");
        }


        /// <summary>
        /// Test the property 'Companyname'
        /// </summary>
        [Test]
        public void CompanynameTest()
        {
            // TODO unit test for the property 'Companyname'
        }
        /// <summary>
        /// Test the property 'Otpcode'
        /// </summary>
        [Test]
        public void OtpcodeTest()
        {
            // TODO unit test for the property 'Otpcode'
        }

    }

}
