# coding: utf-8

"""
    Ytel API V3

    Ytel API version 3  # noqa: E501

    OpenAPI spec version: 3.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.phone_number_api import PhoneNumberApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPhoneNumberApi(unittest.TestCase):
    """PhoneNumberApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.phone_number_api.PhoneNumberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_incomingphone_availablenumber(self):
        """Test case for incomingphone_availablenumber

        Available Numbers  # noqa: E501
        """
        pass

    def test_incomingphone_bulkbuy(self):
        """Test case for incomingphone_bulkbuy

        Bulk Buy Numbers  # noqa: E501
        """
        pass

    def test_incomingphone_buynumber(self):
        """Test case for incomingphone_buynumber

        Purchase Number  # noqa: E501
        """
        pass

    def test_incomingphone_getdidscore(self):
        """Test case for incomingphone_getdidscore

        Get DID Score  # noqa: E501
        """
        pass

    def test_incomingphone_listnumber(self):
        """Test case for incomingphone_listnumber

        List Numbers  # noqa: E501
        """
        pass

    def test_incomingphone_massreleasenumber(self):
        """Test case for incomingphone_massreleasenumber

        Bulk Release  # noqa: E501
        """
        pass

    def test_incomingphone_massupdatenumber(self):
        """Test case for incomingphone_massupdatenumber

        Bulk Update Numbers  # noqa: E501
        """
        pass

    def test_incomingphone_releasenumber_by_response_type_post(self):
        """Test case for incomingphone_releasenumber_by_response_type_post

        Release Number  # noqa: E501
        """
        pass

    def test_incomingphone_transferphonenumbers(self):
        """Test case for incomingphone_transferphonenumbers

        Move Number  # noqa: E501
        """
        pass

    def test_incomingphone_updatenumber(self):
        """Test case for incomingphone_updatenumber

        Update Number  # noqa: E501
        """
        pass

    def test_incomingphone_viewnumber(self):
        """Test case for incomingphone_viewnumber

        View Details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
