# coding: utf-8

"""
    Ytel API V3

    Ytel API version 3  # noqa: E501

    OpenAPI spec version: 3.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.letter_api import LetterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLetterApi(unittest.TestCase):
    """LetterApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.letter_api.LetterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_letter_create(self):
        """Test case for letter_create

        Create Letter  # noqa: E501
        """
        pass

    def test_letter_delete(self):
        """Test case for letter_delete

        Delete Letter  # noqa: E501
        """
        pass

    def test_letter_listsletter(self):
        """Test case for letter_listsletter

        List Letters  # noqa: E501
        """
        pass

    def test_letter_viewletter(self):
        """Test case for letter_viewletter

        View Letter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
