#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Ytel API V3
* Ytel API version 3
*
* OpenAPI spec version: 3.12
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGTemplateData.h"
@protocol SWGTemplateData;
@class SWGTemplateData;



@protocol SWGMessage
@end

@interface SWGMessage : SWGObject

/*  
 */
@property(nonatomic) NSString* apiVersion;
/*  
 */
@property(nonatomic) NSString* messageSid;
/*  
 */
@property(nonatomic) NSString* from;
/*  
 */
@property(nonatomic) NSString* to;
/*  
 */
@property(nonatomic) NSString* messagePrice;
/*  
 */
@property(nonatomic) NSString* body;
/*  
 */
@property(nonatomic) NSString* dateSent;
/*  
 */
@property(nonatomic) NSString* status;
/*  
 */
@property(nonatomic) NSString* templateId;

@property(nonatomic) SWGTemplateData* templateData;

@end
