/* 
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Choose sub account either merge or delete
    /// </summary>
    /// <value>Choose sub account either merge or delete</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MergeNumberStatus
    {
        
        /// <summary>
        /// Enum NUMBER_0 for 0
        /// </summary>
        [EnumMember(Value = 0)]
        NUMBER_0 = 1,
        
        /// <summary>
        /// Enum NUMBER_1 for 1
        /// </summary>
        [EnumMember(Value = 1)]
        NUMBER_1 = 2
    }

}
