<?php
/**
 * TranscriptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TranscriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TranscriptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for transcriptionsAudiourltranscription
     *
     * Transcribe Audio URL.
     *
     */
    public function testTranscriptionsAudiourltranscription()
    {
    }

    /**
     * Test case for transcriptionsListtranscription
     *
     * List Transcriptions.
     *
     */
    public function testTranscriptionsListtranscription()
    {
    }

    /**
     * Test case for transcriptionsRecordingtranscription
     *
     * Transcribe Recording.
     *
     */
    public function testTranscriptionsRecordingtranscription()
    {
    }

    /**
     * Test case for transcriptionsViewtranscription
     *
     * View Transcription.
     *
     */
    public function testTranscriptionsViewtranscription()
    {
    }
}
