/**
* Ytel API V3
* Ytel API version 3
*
* OpenAPI spec version: 3.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
* Choose sub account either merge or delete
* Values: 0,1
*/
enum class MergeNumberStatus(val value: kotlin.Int){

    0("0"),

    1("1");

}

