/**
* Ytel API V3
* Ytel API version 3
*
* OpenAPI spec version: 3.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
* 
* Values: `in`,`out`,both
*/
enum class PlayDtmfDirection(val value: kotlin.String){

    `in`("in"),

    `out`("out"),

    both("both");

}

