=begin
#Ytel API V3

#Ytel API version 3

OpenAPI spec version: 3.11

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.12-1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CallApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CallApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallApi' do
    it 'should create an instance of CallApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CallApi)
    end
  end

  # unit tests for calls_groupcall
  # Group Call
  # Group Call
  # @param from This number to display on Caller ID as calling
  # @param to Please enter multiple E164 number. You can add max 10 numbers. Add numbers separated with comma. e.g : 1111111111,2222222222
  # @param url URL requested once the call connects
  # @param group_confirm_key Define the DTMF that the called party should send to bridge the call. Allowed Values : 0-9, #, *
  # @param group_confirm_file Specify the audio file you want to play when the called party picks up the call
  # @param [Hash] opts the optional parameters
  # @option opts [String] :method Specifies the HTTP method used to request the required URL once call connects.
  # @option opts [String] :status_call_back_url URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
  # @option opts [String] :status_call_back_method Specifies the HTTP methodlinkclass used to request StatusCallbackUrl.
  # @option opts [String] :fall_back_url URL requested if the initial Url parameter fails or encounters an error
  # @option opts [String] :fall_back_method Specifies the HTTP method used to request the required FallbackUrl once call connects.
  # @option opts [String] :heart_beat_url URL that can be requested every 60 seconds during the call to notify of elapsed time and pass other general information.
  # @option opts [String] :heart_beat_method Specifies the HTTP method used to request HeartbeatUrl.
  # @option opts [Integer] :timeout Time (in seconds) we should wait while the call is ringing before canceling the call
  # @option opts [String] :play_dtmf DTMF Digits to play to the call once it connects. 0-9, #, or *
  # @option opts [String] :hide_caller_id Specifies if the caller id will be hidden
  # @option opts [BOOLEAN] :record Specifies if the call should be recorded
  # @option opts [String] :record_call_back_url Recording parameters will be sent here upon completion
  # @option opts [String] :record_call_back_method Method used to request the RecordCallback URL.
  # @option opts [BOOLEAN] :transcribe Specifies if the call recording should be transcribed
  # @option opts [String] :transcribe_call_back_url Transcription parameters will be sent here upon completion
  # @return [String]
  describe 'calls_groupcall test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_interruptcalls
  # Interrupt Call
  # Interrupt the Call by Call Sid
  # @param call_sid The unique identifier for voice call that is in progress.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url URL the in-progress call will be redirected to
  # @option opts [String] :method The method used to request the above Url parameter
  # @option opts [String] :status Status to set the in-progress call to
  # @return [String]
  describe 'calls_interruptcalls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_listcalls
  # List Calls
  # A list of calls associated with your Ytel account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page count to retrieve from the total results in the collection. Page indexing starts at 1.
  # @option opts [Integer] :page_size Number of individual resources listed in the response per page
  # @option opts [String] :to Filter calls that were sent to this 10-digit number (E.164 format).
  # @option opts [String] :from Filter calls that were sent from this 10-digit number (E.164 format).
  # @option opts [String] :date_created Return calls that are from a specified date.
  # @return [String]
  describe 'calls_listcalls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_makecall
  # Make Call
  # You can experiment with initiating a call through Ytel and view the request response generated when doing so and get the response in json
  # @param from A valid Ytel Voice enabled number (E.164 format) that will be initiating the phone call.
  # @param to To number
  # @param url URL requested once the call connects
  # @param [Hash] opts the optional parameters
  # @option opts [String] :method Specifies the HTTP method used to request the required URL once call connects.
  # @option opts [String] :status_call_back_url URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
  # @option opts [String] :status_call_back_method Specifies the HTTP methodlinkclass used to request StatusCallbackUrl.
  # @option opts [String] :fall_back_url URL requested if the initial Url parameter fails or encounters an error
  # @option opts [String] :fall_back_method Specifies the HTTP method used to request the required FallbackUrl once call connects.
  # @option opts [String] :heart_beat_url URL that can be requested every 60 seconds during the call to notify of elapsed tim
  # @option opts [String] :heart_beat_method Specifies the HTTP method used to request HeartbeatUrl.
  # @option opts [Integer] :timeout Time (in seconds) Ytel should wait while the call is ringing before canceling the call
  # @option opts [String] :play_dtmf DTMF Digits to play to the call once it connects. 0-9, #, or *
  # @option opts [BOOLEAN] :hide_caller_id Specifies if the caller id will be hidden
  # @option opts [BOOLEAN] :record Specifies if the call should be recorded
  # @option opts [String] :record_call_back_url Recording parameters will be sent here upon completion
  # @option opts [String] :record_call_back_method Method used to request the RecordCallback URL.
  # @option opts [BOOLEAN] :transcribe Specifies if the call recording should be transcribed
  # @option opts [String] :transcribe_call_back_url Transcription parameters will be sent here upon completion
  # @option opts [String] :if_machine How Ytel should handle the receiving numbers voicemail machine
  # @option opts [String] :if_machine_url URL requested when IfMachine&#x3D;continue
  # @option opts [String] :if_machine_method Method used to request the IfMachineUrl.
  # @option opts [BOOLEAN] :feedback Specify if survey should be enable or not
  # @option opts [String] :survey_id The unique identifier for the survey.
  # @return [String]
  describe 'calls_makecall test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_makervm
  # Send RVM
  # Initiate an outbound Ringless Voicemail through Ytel.
  # @param from A valid Ytel Voice enabled number (E.164 format) that will be initiating the phone call.
  # @param rvm_caller_id A required secondary Caller ID for RVM to work.
  # @param to A valid number (E.164 format) that will receive the phone call.
  # @param voice_mail_url The URL requested once the RVM connects. A set of default parameters will be sent here.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :method Specifies the HTTP method used to request the required URL once call connects.
  # @option opts [String] :status_call_back_url URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
  # @option opts [String] :stats_call_back_method Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
  # @return [String]
  describe 'calls_makervm test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_playaudios
  # Play Audio
  # Play Audio from a url
  # @param call_sid The unique identifier of each call resource
  # @param audio_url URL to sound that should be played. You also can add more than one audio file using semicolons e.g. http://example.com/audio1.mp3;http://example.com/audio2.wav
  # @param say_text Valid alphanumeric string that should be played to the In-progress call.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :length Time limit in seconds for audio play back
  # @option opts [String] :direction The leg of the call audio will be played to
  # @option opts [BOOLEAN] :mix If false, all other audio will be muted
  # @return [String]
  describe 'calls_playaudios test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_recordcalls
  # Record Call
  # Start or stop recording of an in-progress voice call.
  # @param call_sid The unique identifier of each call resource
  # @param record Set true to initiate recording or false to terminate recording
  # @param [Hash] opts the optional parameters
  # @option opts [String] :direction The leg of the call to record
  # @option opts [Integer] :time_limit Time in seconds the recording duration should not exceed
  # @option opts [String] :call_back_url URL consulted after the recording completes
  # @option opts [String] :fileformat Format of the recording file. Can be .mp3 or .wav
  # @return [String]
  describe 'calls_recordcalls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_senddigits
  # Play DTMF
  # Play Dtmf and send the Digit
  # @param call_sid The unique identifier of each call resource
  # @param play_dtmf DTMF digits to play to the call. 0-9, #, *, W, or w
  # @param [Hash] opts the optional parameters
  # @option opts [String] :play_dtmf_direction The leg of the call DTMF digits should be sent to
  # @return [String]
  describe 'calls_senddigits test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_viewcalldetail
  # View Call
  # Retrieve a single voice call’s information by its CallSid.
  # @param call_sid The unique identifier for the voice call.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'calls_viewcalldetail test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_viewcalls
  # View Call
  # Retrieve a single voice call’s information by its CallSid.
  # @param callsid The unique identifier for the voice call.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'calls_viewcalls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for calls_voiceeffect
  # Voice Effect
  # Add audio voice effects to the an in-progress voice call.
  # @param call_sid The unique identifier for the in-progress voice call.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :audio_direction The direction the audio effect should be placed on. If IN, the effects will occur on the incoming audio stream. If OUT, the effects will occur on the outgoing audio stream.
  # @option opts [Float] :pitch_semi_tones Set the pitch in semitone (half-step) intervals. Value between -14 and 14
  # @option opts [Float] :pitch_octaves Set the pitch in octave intervals.. Value between -1 and 1
  # @option opts [Float] :pitch Set the pitch (lowness/highness) of the audio. The higher the value, the higher the pitch. Value greater than 0
  # @option opts [Float] :rate Set the rate for audio. The lower the value, the lower the rate. value greater than 0
  # @option opts [Float] :tempo Set the tempo (speed) of the audio. A higher value denotes a faster tempo. Value greater than 0
  # @return [String]
  describe 'calls_voiceeffect test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
