#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Ytel API V3
* Ytel API version 3
*
* OpenAPI spec version: 3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGSharedShortCodeApi: NSObject <SWGApi>

extern NSString* kSWGSharedShortCodeApiErrorDomain;
extern NSInteger kSWGSharedShortCodeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// List Keywords
/// Retrieve a list of keywords associated with your Ytel account.
///
/// @param page The page count to retrieve from the total results in the collection. Page indexing starts at 1. (optional) (default to 1)
/// @param pagesize Number of individual resources listed in the response per page (optional) (default to 10)
/// @param keyword Only list keywords of keyword (optional)
/// @param shortcode Only list keywords of shortcode (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) keywordListsWithPage: (NSNumber*) page
    pagesize: (NSNumber*) pagesize
    keyword: (NSString*) keyword
    shortcode: (NSNumber*) shortcode
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// View Keyword
/// View a set of properties for a single keyword.
///
/// @param keywordid The unique identifier of each keyword
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) keywordViewWithKeywordid: (NSString*) keywordid
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// List Inbound SMS
/// List All Inbound ShortCode
///
/// @param page The page count to retrieve from the total results in the collection. Page indexing starts at 1. (optional) (default to 1)
/// @param pagesize Number of individual resources listed in the response per page (optional) (default to 10)
/// @param from From Number to Inbound ShortCode (optional)
/// @param shortcode Only list messages sent to this Short Code (optional)
/// @param datecreated Only list messages sent with the specified date (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) shortcodeGetinboundsmsWithPage: (NSNumber*) page
    pagesize: (NSNumber*) pagesize
    from: (NSString*) from
    shortcode: (NSString*) shortcode
    datecreated: (NSString*) datecreated
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// List Shortcodes
/// Retrieve a list of shortcode assignment associated with your Ytel account.
///
/// @param page The page count to retrieve from the total results in the collection. Page indexing starts at 1. (optional) (default to 1)
/// @param pagesize Number of individual resources listed in the response per page (optional) (default to 10)
/// @param shortcode Only list keywords of shortcode (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) shortcodeListshortcodeWithPage: (NSNumber*) page
    pagesize: (NSNumber*) pagesize
    shortcode: (NSString*) shortcode
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Send SMS
/// Send an SMS from a Ytel ShortCode
///
/// @param shortcode The Short Code number that is the sender of this message
/// @param to A valid 10-digit number that should receive the message
/// @param templateid The unique identifier for the template used for the message
/// @param data format of your data, example: {companyname}:test,{otpcode}:1234
/// @param method Specifies the HTTP method used to request the required URL once the Short Code message is sent. (optional) (default to GET)
/// @param messageStatusCallback URL that can be requested to receive notification when Short Code message was sent. (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) shortcodeSendsmsWithShortcode: (NSString*) shortcode
    to: (NSString*) to
    templateid: (NSString*) templateid
    data: (NSString*) data
    method: (NSString*) method
    messageStatusCallback: (NSString*) messageStatusCallback
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Update Shortcode
/// Update Assignment
///
/// @param shortcode List of valid shortcode to your Ytel account
/// @param friendlyName User generated name of the shortcode (optional)
/// @param callbackUrl URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished. (optional)
/// @param callbackMethod Specifies the HTTP method used to request the required StatusCallBackUrl once call connects. (optional)
/// @param fallbackUrl URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST. (optional)
/// @param fallbackUrlMethod Specifies the HTTP method used to request the required FallbackUrl once call connects. (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) shortcodeUpdateshortcodeWithShortcode: (NSString*) shortcode
    friendlyName: (NSString*) friendlyName
    callbackUrl: (NSString*) callbackUrl
    callbackMethod: (NSString*) callbackMethod
    fallbackUrl: (NSString*) fallbackUrl
    fallbackUrlMethod: (NSString*) fallbackUrlMethod
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// View Shortcode
/// The response returned here contains all resource properties associated with the given Shortcode.
///
/// @param shortcode List of valid Shortcode to your Ytel account
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) shortcodeViewshortcodeWithShortcode: (NSString*) shortcode
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// List Templates
/// List Shortcode Templates by Type
///
/// @param type The type (category) of template Valid values: marketing, authorization (optional) (default to authorization)
/// @param page The page count to retrieve from the total results in the collection. Page indexing starts at 1. (optional) (default to 1)
/// @param pagesize The count of objects to return per page. (optional) (default to 10)
/// @param shortcode Only list templates of type (optional)
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) templateListsWithType: (NSString*) type
    page: (NSNumber*) page
    pagesize: (NSNumber*) pagesize
    shortcode: (NSString*) shortcode
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// View Template
/// View a Shared ShortCode Template
///
/// @param templateId The unique identifier for a template object
/// 
///  code:200 message:""
///
/// @return NSString*
-(NSURLSessionTask*) templateViewWithTemplateId: (NSString*) templateId
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
